config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }

  devise_scope :person do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_person_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_person_session
  end

  get 'officer_page', action: :index, controller: 'officer_pages'
  get 'admins', action: :index, controller: :admins
  resources :officer_pages
  resources :home_pages
  resources :contact_forms
  resources :companies
  resources :alumnis
  resources :officers
  resources :positions
  resources :people
  resources :schedules
  post 'admins', action: :change_email, controller: 'admins'

  root 'home_pages#index'
end

app/models/officer.rb
# frozen_string_literal: true

class Officer < ApplicationRecord
     validates :person_id, :position, :year_elected, :description, presence: true
     belongs_to :person
     has_many :contact_forms
     has_one_attached :portrait
end

app/controllers/officers_controller.rb
# frozen_string_literal: true

class OfficersController < ApplicationController
     before_action :authenticate_person!
     before_action :set_officer, only: %i[show edit update destroy]

     # GET /officers or /officers.json
     def index
          @officers = Officer.all
     end

     # GET /officers/1 or /officers/1.json
     def show; end

     # GET /officers/new
     def new
          @officer = Officer.new
     end

     # GET /officers/1/edit
     def edit; end

     # POST /officers or /officers.json
     def create
          @officer = Officer.new(officer_params)
          respond_to do |format|
               if @officer.save
                    format.html { redirect_to(officer_url(@officer), notice: 'Officer was successfully created.') }
                    format.json { render(:show, status: :created, location: @officer) }
               else
                    format.html { render(:new, status: :unprocessable_entity) }
                    format.json { render(json: @officer.errors, status: :unprocessable_entity) }
               end
          end
     end

     # PATCH/PUT /officers/1 or /officers/1.json
     def update
          respond_to do |format|
               if @officer.update(officer_params)
                    format.html { redirect_to(officer_url(@officer), notice: 'Officer was successfully updated.') }
                    format.json { render(:show, status: :ok, location: @officer) }
               else
                    format.html { render(:edit, status: :unprocessable_entity) }
                    format.json { render(json: @officer.errors, status: :unprocessable_entity) }
               end
          end
     end

     # DELETE /officers/1 or /officers/1.json
     def destroy
          @officer.destroy!

          respond_to do |format|
               format.html { redirect_to(officers_url, notice: 'Officer was successfully destroyed.') }
               format.json { head(:no_content) }
          end
     end

     private

     # Use callbacks to share common setup or constraints between actions.
     def set_officer
          @officer = Officer.find(params[:id])
     end

     # Only allow a list of trusted parameters through.
     def officer_params
          params.require(:officer).permit(:position, :email, :year_elected, :description, :person_id, :portrait)
     end
end

app/helpers/officers_helper.rb
# frozen_string_literal: true

module OfficersHelper
end

app/views/officers/_form.html.erb
<%= form_with(model: officer) do |form| %>
  <% if officer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(officer.errors.count, "error") %> prohibited this officer from being saved:</h2>

      <ul>
        <% officer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields">
    <div class="form-row">
      <div class="form-group col-md-3">
      <%= form.label :position, {class: 'form-label'} %>
      <%= form.text_field :position, {class: "form-control"} %>
      </div>
    </div>


    <div class="form-row">
      <div class="form-group col-md-3">
      <%= form.label :year_elected, {class: 'form-label'} %>
      <%= form.text_field :year_elected, {class: "form-control"} %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-3">
      <%= form.label :description, {class: 'form-label'} %>
      <%= form.text_field :description, {class: "form-control"} %>
      </div>
    </div>


    <div class="form-row">
      <div class="form-group col-md-3">
      <%= form.label :person_id, {class: 'form-label'} %>
      <% if officer.blank? %>

        <%= form.select :person_id, Person.where.not(id: Officer.select(:person_id))
                        .order(:name).map { |person| [person.name, person.id] },
                        {include_blank: true, id: "officer_person_id"}, {class: "form-control"}%>
      <%else %>
        <%= form.select :person_id,
                        Person.where.not(id: Officer.select(:person_id))
                          .or(Person.where(id: officer.person_id)).order(:name).map { |person| [person.name, person.id] },
                        {include_blank: true, id: "officer_person_id"}, {class: "form-control"}%>
      <%end %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-3">
      <%= form.label :portrait, {class: 'form-label'} %>
      <% if officer.portrait.attached? %>
        <%= image_tag officer.portrait %><br>
      <% end %>
      <%= form.file_field :portrait, {accept: 'image/png, image/gif, image/jpeg', class: "form-control"}%>
      </div>
    </div>
  </div>

  <div class="submit-button">
    <%= form.button :submit => "", class: "btn btn-success" %>
  </div>
<% end %>

app/views/officers/edit.html.erb
<div class="title p-5">
  <h1>Editing Officer</h1>
</div>


<%= render 'form', officer: @officer %>

<div class="submit-button">
  <%= link_to 'Show', @officer, :class=> "btn btn-primary" %>
</div>
<div class="submit-button">
  <%= link_to 'Back', officers_path, :class=> "btn btn-warning" %>
</div>

app/views/officers/index.html.erb
<div class="p-5">
  <h1>Officers</h1>
</div>

<div class="submit-button">
  <%= link_to 'New Officer', new_officer_path, :class => "btn btn-success"   %>
</div>

<div class="outer-table-div">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Position</th>
      <th scope="col">Email</th>
      <th scope="col">Year elected</th>
      <th scope="col">Description</th>
      <th scope="col">Photo</th>
      <th scope="col">Person</th>
      <th scope="col" colspan="3" style="text-align:center;" >Options</th>
    </tr>
    </thead>

    <tbody>
    <% @officers.each do |officer| %>
      <tr scope="row" >
        <td><%= officer.position %></td>
        <td><%= officer.person.email %></td>
        <td><%= officer.year_elected %></td>
        <td><%= officer.description %></td>
        <td><%= officer.portrait.filename.to_s %></td>
        <td><%= officer.person.name %></td>
        <td><%= link_to 'Show', officer, :class => "btn btn-outline-info"%></td>
        <td><%= link_to 'Edit', edit_officer_path(officer), :class => "btn btn-outline-info"  %></td>
        <td><%= link_to 'Destroy', officer, method: :delete, data: { confirm: 'Are you sure?' },
                        :class => "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/officers/new.html.erb
<div class="title p-5">
  <h1>New Officer</h1>
</div>


<%= render 'form', officer: @officer %>

<div class="submit-button">
  <%= link_to 'Back', officers_path, :class=>"btn btn-dark"  %>
</div>

app/views/officers/show.html.erb
<div class="row justify-content-center p-7">
  <div class="card" style="text-align: center; width: 18rem;">
    <% if @officer.portrait.attached? %>
      <%= image_tag @officer.portrait.variant(resize_to_fit: [200, 200]), :class=>"card-img-top" %>
    <% else %>
      No image attached
    <% end %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <strong><h5>Officer Name: </h5></strong>
        <%= @officer.person.name %>
      </li>
      <li class="list-group-item">
        <strong><h5>Position: </h5></strong>
        <%= @officer.position %>
      </li>
      <li class="list-group-item">
        <strong><h5>Year Elected: </h5></strong>
        <%= @officer.year_elected %>
      </li>
      <li class="list-group-item">
        <strong><h5>Description: </h5></strong>
        <%= @officer.description%>
      </li>
    </ul>
    <div class="card-footer">
      <%= link_to 'Edit', edit_officer_path(@officer), :class=>"btn btn-warning" %>
      <%= link_to 'Edit Person Details', edit_person_path(@officer.person), :class=>"btn btn-warning" %>
    </div>
  </div>
</div>

<div class="submit-button">
  <%= link_to 'Back', officers_path, :class=>"btn btn-dark"   %>
</div>