config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }

  devise_scope :person do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_person_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_person_session
  end

  get 'officer_page', action: :index, controller: 'officer_pages'
  get 'admins', action: :index, controller: :admins
  resources :officer_pages
  resources :home_pages
  resources :contact_forms
  resources :companies
  resources :alumnis
  resources :officers
  resources :positions
  resources :people
  resources :schedules
  post 'admins', action: :change_email, controller: 'admins'

  root 'home_pages#index'
end

app/models/alumni.rb
# frozen_string_literal: true

class Alumni < ApplicationRecord
     validates :graduation_year, :person_id, presence: true
     belongs_to :person
end

app/controllers/alumnis_controller.rb
# frozen_string_literal: true

class AlumnisController < ApplicationController
     before_action :authenticate_person!
     before_action :set_alumni, only: %i[show edit update destroy]

     # GET /alumnis or /alumnis.json
     def index
          @alumnis = Alumni.all
     end

     # GET /alumnis/1 or /alumnis/1.json
     def show; end

     # GET /alumnis/new
     def new
          @alumni = Alumni.new
     end

     # GET /alumnis/1/edit
     def edit; end

     # POST /alumnis or /alumnis.json
     def create
          @alumni = Alumni.new(alumni_params)

          respond_to do |format|
               if @alumni.save
                    format.html { redirect_to(alumni_url(@alumni), notice: 'Alumni was successfully created.') }
                    format.json { render(:show, status: :created, location: @alumni) }
               else
                    format.html { render(:new, status: :unprocessable_entity) }
                    format.json { render(json: @alumni.errors, status: :unprocessable_entity) }
               end
          end
     end

     # PATCH/PUT /alumnis/1 or /alumnis/1.json
     def update
          respond_to do |format|
               if @alumni.update(alumni_params)
                    format.html { redirect_to(alumni_url(@alumni), notice: 'Alumni was successfully updated.') }
                    format.json { render(:show, status: :ok, location: @alumni) }
               else
                    format.html { render(:edit, status: :unprocessable_entity) }
                    format.json { render(json: @alumni.errors, status: :unprocessable_entity) }
               end
          end
     end

     # DELETE /alumnis/1 or /alumnis/1.json
     def destroy
          @alumni.destroy!

          respond_to do |format|
               format.html { redirect_to(alumnis_url, notice: 'Alumni was successfully destroyed.') }
               format.json { head(:no_content) }
          end
     end

     private

     # Use callbacks to share common setup or constraints between actions.
     def set_alumni
          @alumni = Alumni.find(params[:id])
     end

     # Only allow a list of trusted parameters through.
     def alumni_params
          params.require(:alumni).permit(:graduation_year, :person_id)
     end
end

app/helpers/alumnis_helper.rb
# frozen_string_literal: true

module AlumnisHelper
end

app/views/alumnis/_form.html.erb
<%= form_with(model: alumni) do |form| %>
  <% if alumni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alumni.errors.count, "error") %> prohibited this alumni from being saved:</h2>

      <ul>
        <% alumni.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields">
    <div class="form-row">
      <div class="form-group col-md-3">
        <%= form.label :person_id, {class: 'form-label'} %>
        <%= form.select :person_id, Person.order(:name).map { |person| [person.name, person.id] }, {include_blank: true, id: "alumni_person_id"}, {class: "form-control"} %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-3">
        <%= form.label :graduation_year, {class: 'form-label'}%>
        <%= form.text_field :graduation_year, { class: "form-control"}%>
      </div>
    </div>
  </div>

<div class="submit-button">
  <%= form.button :submit => "", class: "btn btn-success" %>
</div>


<% end %>

app/views/alumnis/edit.html.erb
<div class="title p-5">
  <h1>Editing Alumni</h1>
</div>


<%= render 'form', alumni: @alumni %>

<div class="submit-button">
  <%= link_to 'Show', @alumni, :class=> "btn btn-primary" %>
</div>

<div class="submit-button">
  <%= link_to 'Back', alumnis_path, :class=> "btn btn-dark" %>
</div>

app/views/alumnis/index.html.erb
<div class="p-5">
  <h1>Alumnis</h1>
</div>


<div class="submit-button">
  <%= link_to 'New Alumni', new_alumni_path, :class => "btn btn-success"  %>
</div>



<div class="outer-table-div">
  <table class="table">
    <thead>
      <tr>
        <th scope="col" >Graduation year</th>
        <th scope="col" >Companies worked</th>
        <th scope="col" >Person</th>
        <th scope="col" colspan="3" style="text-align:center;" >Options</th>
      </tr>
    </thead>

    <tbody >
      <% @alumnis.each do |alumni| %>
        <tr scope="row" >
          <td><%= alumni.graduation_year %></td>
          <td><% Position.where(person_id: alumni.person_id).each do |positon| %>
                <%=positon.company.name %>,
              <% end %>
              </td>
          <td><%= Person.find(alumni.person_id).name %></td>
          <td><%= link_to 'Show', alumni, :class => "btn btn-outline-info"%></td>
          <td><%= link_to 'Edit', edit_alumni_path(alumni), :class => "btn btn-outline-info" %></td>
          <td><%= link_to 'Destroy', alumni, method: :delete, data: { confirm: 'Are you sure?' },
                          :class => "btn btn-outline-danger"%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/alumnis/new.html.erb
<div class="title p-5">
  <h1>New Alumni</h1>
</div>


<%= render 'form', alumni: @alumni %>

<div class="submit-button">
  <%= link_to 'Back', alumnis_path, :class=>"btn btn-dark"  %>
</div>

app/views/alumnis/show.html.erb
<div class="row justify-content-center p-7">
  <div class="card" style="text-align: center; width: 18rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <strong><h5>Person Name: </h5></strong>
        <%= @alumni.person.name %>
      </li>
      <li class="list-group-item">
        <strong><h5>Graduation Year: </h5></strong>
        <%= @alumni.graduation_year %>
      </li>
      <li class="list-group-item">
        <strong><h5>Companies Worked: </h5></strong>
        <p class="card-text">
          <% Position.where(person_id: @alumni.person_id).each do |position| %>
            <%=position.company.name %>
          <% end %>
        </p>
      </li>
    </ul>
    <div class="card-footer">
        <%= link_to 'Edit', edit_alumni_path(@alumni), :class=>"btn btn-warning"   %>

    </div>
  </div>
</div>

<div class="submit-button">
  <%= link_to 'Back', alumnis_path, :class=>"btn btn-dark"   %>
</div>