config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }

  devise_scope :person do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_person_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_person_session
  end

  get 'officer_page', action: :index, controller: 'officer_pages'
  get 'admins', action: :index, controller: :admins
  resources :officer_pages
  resources :home_pages
  resources :contact_forms
  resources :companies
  resources :alumnis
  resources :officers
  resources :positions
  resources :people
  resources :schedules
  post 'admins', action: :change_email, controller: 'admins'

  root 'home_pages#index'
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
     validates :website, :name, presence: true
     has_many :positions
     has_one_attached :logo
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
     before_action :authenticate_person!
     before_action :set_company, only: %i[show edit update destroy]

     # GET /companies or /companies.json
     def index
          @companies = Company.all
     end

     # GET /companies/1 or /companies/1.json
     def show; end

     # GET /companies/new
     def new
          @company = Company.new
     end

     # GET /companies/1/edit
     def edit; end

     # POST /companies or /companies.json
     def create
          @company = Company.new(company_params)

          respond_to do |format|
               if @company.save
                    format.html { redirect_to(company_url(@company), notice: 'Company was successfully created.') }
                    format.json { render(:show, status: :created, location: @company) }
               else
                    format.html { render(:new, status: :unprocessable_entity) }
                    format.json { render(json: @company.errors, status: :unprocessable_entity) }
               end
          end
     end

     # PATCH/PUT /companies/1 or /companies/1.json
     def update
          respond_to do |format|
               if @company.update(company_params)
                    format.html { redirect_to(company_url(@company), notice: 'Company was successfully updated.') }
                    format.json { render(:show, status: :ok, location: @company) }
               else
                    format.html { render(:edit, status: :unprocessable_entity) }
                    format.json { render(json: @company.errors, status: :unprocessable_entity) }
               end
          end
     end

     # DELETE /companies/1 or /companies/1.json
     def destroy
          @company.destroy!

          respond_to do |format|
               format.html { redirect_to(companies_url, notice: 'Company was successfully destroyed.') }
               format.json { head(:no_content) }
          end
     end

     private

     # Use callbacks to share common setup or constraints between actions.
     def set_company
          @company = Company.find(params[:id])
     end

     # Only allow a list of trusted parameters through.
     def company_params
          params.require(:company).permit(:name, :website, :logo)
     end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields">
    <div class="form-row">
      <div class="form-group col-md-3">
        <%= form.label :name, {class: 'form-label'} %>
        <%= form.text_field :name, { class: "form-control"} %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-3">
        <%= form.label :website, {class: 'form-label'} %>
        <%= form.text_field :website, { class: "form-control"} %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-3">
      <%= form.label :logo, {class: 'form-label'} %>
      <% if company.logo.attached? %>
        <%= image_tag company.logo %><br>
      <% end %>
      <%= form.file_field :logo, {accept: 'image/png, image/gif, image/jpeg, image/svg', class: "form-control"}%>
      </div>
    </div>
  </div>


  <div class="submit-button">
    <%= form.button :submit => "", class: "btn btn-success" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="submit-button p-5">
  <h1>Editing Company</h1>
</div>


<%= render 'form', company: @company %>

<div class="submit-button">
  <%= link_to 'Show', @company, :class=> "btn btn-primary" %>
</div>
<div class="submit-button">
  <%= link_to 'Back', companies_path, :class=> "btn btn-warning" %>
</div>

app/views/companies/index.html.erb
<div class="title p-5">
  <h1>Companies</h1>
</div>

<div class="submit-button">
  <%= link_to 'New Company', new_company_path, :class => "btn btn-success" %>
</div>

<div class="outer-table-div">
  <table class="table">
    <thead>
    <tr>
      <th scope="col" >Company Name</th>
      <th scope="col" >Company website</th>
      <th scope="col" >Company logo</th>
      <th scope="col"  colspan="3" style="text-align:center;"> Options </th>
    </tr>
    </thead>

    <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.website %></td>
        <td><%= company.logo.filename.to_s %></td>
        <td><%= link_to 'Show', company, :class => "btn btn-outline-info" %></td>
        <td><%= link_to 'Edit', edit_company_path(company), :class => "btn btn-outline-info" %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/companies/new.html.erb
<div class="title p-5">
  <h1>New Company</h1>
</div>


<%= render 'form', company: @company %>
<div class="submit-button">
  <%= link_to 'Back', companies_path, :class=>"btn btn-dark"  %>
</div>

app/views/companies/show.html.erb
<div class="row justify-content-center p-7">
  <div class="card" style="text-align: center; width: 18rem;">
    <% if @company.logo.attached? %>
      <%= image_tag @company.logo.variant(resize_to_fit: [200, 200]), :class=>"card-img-top" %>
    <% else %>
      No image attached
    <% end %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <strong><h5>Company Name: </h5></strong>
        <%= @company.name %>
      </li>
      <li class="list-group-item">
        <strong><h5>Company Website: </h5></strong>
        <a href="https://<%=@company.website%>"><%= @company.website %></a>
      </li>
    </ul>
    <div class="card-footer">
      <%= link_to 'Edit',  edit_company_path(@company), :class=>"btn btn-warning"   %>
    </div>
  </div>
</div>


<div class="submit-button">
  <%= link_to 'Back', companies_path, :class=>"btn btn-dark"   %>
</div>