config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }

  devise_scope :person do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_person_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_person_session
  end

  get 'officer_page', action: :index, controller: 'officer_pages'
  get 'admins', action: :index, controller: :admins
  resources :officer_pages
  resources :home_pages
  resources :contact_forms
  resources :companies
  resources :alumnis
  resources :officers
  resources :positions
  resources :people
  resources :schedules
  post 'admins', action: :change_email, controller: 'admins'

  root 'home_pages#index'
end

app/models/alumni.rb
# frozen_string_literal: true

class Alumni < ApplicationRecord
     validates :graduation_year, :person_id, presence: true
     belongs_to :person
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
     self.abstract_class = true
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
     validates :website, :name, presence: true
     has_many :positions
     has_one_attached :logo
end

app/models/contact_form.rb
# frozen_string_literal: true

class ContactForm < ApplicationRecord
     validates :person_id, :email, :name, :message, presence: true
     has_many :officer
     has_many :person, through: :officer
end

app/models/officer.rb
# frozen_string_literal: true

class Officer < ApplicationRecord
     validates :person_id, :position, :year_elected, :description, presence: true
     belongs_to :person
     has_many :contact_forms
     has_one_attached :portrait
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
     devise :omniauthable, omniauth_providers: [:google_oauth2]

     validates :name, :class_year, :membership_length, :email, presence: true
     has_many :positions, dependent: :destroy # This will delete all the positions to the person when person is deleted
     has_many :companies, through: :positions
     has_many :contact_forms, through: :officers
     has_one :officer, dependent: :destroy # Will delete officer when person is deleted
     has_one :alumni, dependent: :destroy # Will delete alumni when person is deleted

     def self.from_omniauth(auth)
          Person.where(email: auth.info.email, is_admin: true).first
     end
end

app/models/position.rb
# frozen_string_literal: true

class Position < ApplicationRecord
     validates :position, :company_id, :person_id, presence: true
     belongs_to :person
     belongs_to :company
end

app/controllers/admins_controller.rb
# frozen_string_literal: true

class AdminsController < ApplicationController
     before_action :authenticate_person!
     # GET /admins or /admins.json
     def index
     end
     def change_email
          if params[:address] == ""
               redirect_to admins_path
               flash[:error] = "Must provide an email"
          elsif params[:address].include? ".com"
               $calendar_email = params[:address]
               redirect_to admins_path
               flash[:success] =  "Email has been successfully changed"
          elsif params[:address].include? ".edu"
               $calendar_email = params[:address]
               redirect_to admins_path
               flash[:success] =  "Email has been successfully changed"
          else
               redirect_to admins_path
               flash[:error] = "Must provide a valid email with proper extension"
          end
     end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
     before_action :authenticate_person!
     before_action :set_person, only: %i[show edit update destroy]

     # GET /people or /people.json
     def index
          @people = Person.all
     end

     # GET /people/1 or /people/1.json
     def show; end

     # GET /people/new
     def new
          @person = Person.new
     end

     # GET /people/1/edit
     def edit; end

     # POST /people or /people.json
     def create
          @person = Person.new(person_params)

          respond_to do |format|
               if @person.save
                    format.html { redirect_to(person_url(@person), notice: 'Person was successfully created.') }
                    format.json { render(:show, status: :created, location: @person) }
               else
                    format.html { render(:new, status: :unprocessable_entity) }
                    format.json { render(json: @person.errors, status: :unprocessable_entity) }
               end
          end
     end

     # PATCH/PUT /people/1 or /people/1.json
     def update
          respond_to do |format|
               if @person.update(person_params)
                    format.html { redirect_to(person_url(@person), notice: 'Person was successfully updated.') }
                    format.json { render(:show, status: :ok, location: @person) }
               else
                    format.html { render(:edit, status: :unprocessable_entity) }
                    format.json { render(json: @person.errors, status: :unprocessable_entity) }
               end
          end
     end

     # DELETE /people/1 or /people/1.json
     def destroy
          @person.destroy!

          respond_to do |format|
               format.html { redirect_to(people_url, notice: 'Person was successfully destroyed.') }
               format.json { head(:no_content) }
          end
     end

     private

     # Use callbacks to share common setup or constraints between actions.
     def set_person
          @person = Person.find(params[:id])
     end

     # Only allow a list of trusted parameters through.
     def person_params
          params.require(:person).permit(:name, :class_year, :membership_length, :email, :is_admin)
     end
end

app/helpers/admins_helper.rb
# frozen_string_literal: true

module AdminsHelper
end

app/helpers/alumnis_helper.rb
# frozen_string_literal: true

module AlumnisHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
    def flash_class(level)
        bootstrap_alert_class = {
          "success" => "alert-success",
          "error" => "alert-danger",
          "notice" => "alert-info",
          "alert" => "alert-danger",
          "warn" => "alert-warning"
        }
        bootstrap_alert_class[level]
      end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/helpers/contact_forms_helper.rb
# frozen_string_literal: true

module ContactFormsHelper
end

app/helpers/home_pages_helper.rb
# frozen_string_literal: true

module HomePagesHelper
end

app/helpers/officer_pages_helper.rb
# frozen_string_literal: true

module OfficerPagesHelper
end

app/helpers/officers_helper.rb
# frozen_string_literal: true

module OfficersHelper
end

app/helpers/people_helper.rb
# frozen_string_literal: true

module PeopleHelper
end

app/helpers/positions_helper.rb
# frozen_string_literal: true

module PositionsHelper
end

app/helpers/schedules_helper.rb
# frozen_string_literal: true

module SchedulesHelper
end

app/views/admins/index.html.erb
<div class="container p-5">
  <h1 style ="text-align: center;">Welcome to the Admins Page!</h1>


  <h4>General Guidelines</h4>
  <ul>
    <li>Navigate to the desired area using the Admin Menu.</li>
    <li>The initial page will show the list of items for the selected area along with some options.</li>
  </ul>
    <h5>Options</h5>
  <ul>
    <li>New items can be via <div class="submit-button"><div class="btn btn-success"> New ITEM </div></div></li>
    <li>Item information is displayed using <div class="submit-button"><div class="btn btn-outline-info"> Show </div></div></li>
    <li>Items can be edited using <div class="submit-button"><div class="btn btn-outline-info"> Edit </div></div> </li>
    <li>Items can be deleted using <div class="submit-button"><div class="btn btn-outline-danger">Destroy</div></div></li>
  </ul>
  <br>
  <h4>Specifics On Areas</h4>
  <h5>People/Members</h5>
  <p>
    The people/member table is the basis for certain other tables. It is required for a person
    to exist before adding an <strong>Officer</strong> or an <strong>Alumni</strong>
  </p>
  <p>
    Deleting a person will delete the following items associated with that person:
  </p>
  <ul>
    <li>Officer</li>
    <li>Alumni</li>
    <li>Position</li>
  </ul>


  <h5>Admins</h5>
  <p>
    Admins are added and removed via editing items in the people section. An existing admin can update a person to be
    an admin by editing a person item, checking the 'is_admin' box.
    Similar, an admin can be removed by unchecking this box.
  </p>
  <p>The email associated with the person is what needs to be used when logging in.</p>


  <h5>Officers</h5>
  <p><strong>
    An officer can only be made after creating a person with the base information.
  </strong></p>
  <p>
    Officers may have a photo that can be uploaded when creating or editing an officer.
    No photo being uploaded will result in a default silhouette image being used.
  </p>
  <p>
    The officers listed in the Officer table are displayed in the public officer page.
  </p>

  <h5>Alumni</h5>
  <p><strong>
    An Alumni can only be made after creating a person with the base information.
  </strong></p>
  <p>
    The alumni page is used to populated the list of alumni display on the main page.
  </p>


  <h5>Company</h5>
  <p>
    The company area is used to populated the list of companies displayed on the main page.
    It allows create and updating a list of companies with their logo, name, and website.
  </p>

  <h5>Position</h5>
  <p>
    This area is for linking a person to a company.
    With this an admin can list who worked at what company at what position in said company.
  </p>

  <h5>Contact Form</h5>
  <p>
    This area allows for viewing the list of messages submit via the public contact form.
    It displays the intended officer, the email of the user, the name of user, and their message.
  </p>

  <h5>Schedule</h5>
  <p>
    The calendar on the schedule page can be changed by filling in the text box below with a valid email that 
    is linked to a Google Calendar. 
  </p>
  <p><strong>
    Make sure the events are public for the Google Calendar that is tied to the new email; 
    otherwise the events will not show up on the schedule page.
  </strong>
  </p>

  <%= form_with do |form| %>
    <div class = "form-row align-items-center">
      <div class = "mx-sm-1">
        <%= form.email_field :address, :class => "form-control"%>
      </div>
      <div class = "mx-sm-1">
        <%= form.submit "Change Email", :class => "submit-button btn btn-success"%>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<footer >
    <div class="container" >
    <div style="text-align: center">
        <div style = "border-top: double" class="navbar-text ">
            <h4 > American Association of Drilling Engineers </h4>
            <a href="https://www.instagram.com/aadetamu/?hl=en" class="Instagram"  style="font-size: 30px; ;margin-right:25px"><i class="fa fa-instagram"></i></a>
            <a href="https://www.aade.org/" class="link"  style="font-size: 30px"><i class="fa fa-link"></i></a>
            <a href="https://www.linkedin.com/in/aade-tamu/recent-activity/" class="linkedin"  style="font-size: 30px; margin-left:25px"><i class="fa fa-linkedin"></i></a>


        </div>
    </div>
    </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong fixed-top" style="background-color: #2E1114;">
  <a class="navbar-brand" href="/home_pages">AADE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link <%if current_page?(home_pages_path) or current_page?(root_path) %>active <% end %>" href="/home_pages">Home<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link <%if current_page?(schedules_path) %>active <% end %>" href="/schedules" >Schedule</a>
      <a class="nav-item nav-link <%if current_page?(officer_pages_path) %>active <% end %>" href="/officer_pages" >Officer Page</a>
      <% if person_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Admin Menu
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/admins">Admin Home</a></li>
            <li><a class="dropdown-item" href="/people">Manage Members</a></li>
            <li><a class="dropdown-item" href="/officers">Manage Officers</a></li>
            <li><a class="dropdown-item" href="/alumnis">Manage Alumni</a></li>
            <li><a class="dropdown-item" href="/companies">Manage Companies</a></li>
            <li><a class="dropdown-item" href="/positions">Manage Positions</a></li>
            <li><a class="dropdown-item" href="/contact_forms">Manage Contact Forms</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/admins/sign_out">Sign Out</a></li>
          </ul>
        </li>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Bootstrap 4.0-->
    <!-- How to get Bootstrap to work (timestamp 1:21:33): https://www.youtube.com/watch?v=fmyvWz5TUWg -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>AADE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'global_style' %>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <%= render 'layouts/nav' %>
  <!-- This checks what page is currently displayed and renders the correct navbar -->
  <% if  not (current_page?(home_pages_path) or
          current_page?(schedules_path) or
          current_page?(officer_pages_path) or
          current_page?(root_path))%>
  <%= stylesheet_link_tag 'admins' %>
  <% end %>

  <body>
  <% if flash.any? %>
  <% flash.each do |key, message| %>
    <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center fixed-top" role="alert" style="margin-top: 65px">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
      <script type="text/javascript">
          setTimeout(function () {

              // Closing the alert
              $('.<%= flash_class(key) %>').alert('close');
          }, 5000);
      </script>
  <% end %>
  <% end %>
  <%= yield %>

  <% if  current_page?(home_pages_path) or
  current_page?(schedules_path) or
  current_page?(officer_pages_path) or
  current_page?(root_path)%>
  <%= render 'layouts/footer' %>
  <% end %>
  
  </body>
</html>